const Actions = {
    RESET_STATE: "RESET_STATE",
    
    GET_RANDOM_CATEGORIES_DATA:"GET_RANDOM_CATEGORIES",
    GET_RANDOM_CATEGORIES_SUCCESS:"GET_RANDOM_cATEGORIES_SUCCESS",
    GET_RANDOM_CATEGORIES_FAIL:"GET_RANDOM_CATEGORIES_FAIL",

    //HomePage all categories
    GET_ALL_CATEGORIES_DATA:"GET_ALL_CATEGORIES_DATA",
    GET_ALL_CATEGORIES_SUCCESS:"GET_ALL_CATEGORIES_SUCCESS",
    GET_ALL_CATEGORIES_FAIL:"GET_ALL_CATEGORIES_FAIL"
}

export default Actions