 const actions = {
    RESET_STATE: "RESET_STATE",

    PRODUCT_CATEGORY_DATA:"PRODUCT_CATEGORY_DATA",
    PRODUCT_CATEGORY_SUCCESS:"PRODUCT_CATEGORY_SUCCESS",
    PRODUCT_CATEGORY_FAIL:"PRODUCT_CATEGORY_FAIL"
}

export default actions