const actions = {
    RESET_STATE: "RESET_STATE",

    POST_PRODUCT_DATA:"POST_PRODUCT_DATA",
    POST_PRODUCT_SUCCESS:"POST_PRODUCT_SUCCESS",
    POST_PRODUCT_FAIL:"POST_PRODUCT_FAIL",

    //get All products
    GET_All_PRODUCTS_DATA:"GET_All_PRODUCTS_DATA",
    GET_ALL_PRODUCTS_SUCCESS:"GET_ALL_PRODUCTS_SUCCESS",
    GET_ALL_PRODUCTS_FAIL:"GET_ALL_PRODUCTS_FAIL"
}

export default actions