const actions = {
    RESET_STATE: "RESET_STATE",

    POST_PRODUCT_DATA:"POST_PRODUCT_DATA",
    POST_PRODUCT_SUCCESS:"POST_PRODUCT_SUCCESS",
    POST_PRODUCT_FAIL:"POST_PRODUCT_FAIL",

    //get All products
    GET_All_PRODUCTS_DATA:"GET_All_PRODUCTS_DATA",
    GET_ALL_PRODUCTS_SUCCESS:"GET_ALL_PRODUCTS_SUCCESS",
    GET_ALL_PRODUCTS_FAIL:"GET_ALL_PRODUCTS_FAIL",

    //get Product by id
    GET_PRODUCT_BY_ID_DATA:"GET_PRODUCT_BY_ID_DATA",
    GET_PRODUCT_BY_ID_DATA_SUCCESS:"GET_PRODUCT_BY_ID_DATA_SUCCESS",
    GET_PRODUCT_BY_ID_DATA_FAIL:"GET_PRODUCT_BY_ID_DATA_FAIL",

    //update Product by id
    UPDATE_PRODUCT_BY_ID_DATA:"UPDATE_PRODUCT_BY_ID_DATA",
    UPDATE_PRODUCT_BY_ID_DATA_SUCCESS:"UPDATE_PRODUCT_BY_ID_DATA_SUCCESS",
    UPDATE_PRODUCT_BY_ID_DATA_FAIL:"UPDATE_PRODUCT_BY_ID_DATA_FAIL",

    //delete Product by id
    DELETE_PRODUCT_BY_ID_DATA:"DELETE_PRODUCT_BY_ID_DATA",
    DELETE_PRODUCT_BY_ID_DATA_SUCCESS:"DELETE_PRODUCT_BY_ID_DATA_SUCCESS",
    DELETE_PRODUCT_BY_ID_DATA_FAIL:"DELETE_PRODUCT_BY_ID_DATA_FAIL",

   //getProductDetails by id
   PRODUCT_DETAILS_BY_ID:"PRODUCT_DETAILS_BY_ID",
   PRODUCT_DETAILS_BY_ID_SUCCESS:"PRODUCT_DETAILS_BY_ID_SUCCESS",
   PRODUCT_DETAILS_BY_ID_FAIL:"PRODUCT_DETAILS_BY_ID_FAIL",

   //cartItems
   CART_ITEMS_SUCCESS:"CART_ITEMS_SUCCESS",
   CART_ITEMS_FAIL:"CART_ITEMS_FAIL",

   //Inc_Cart_Data
   INC_QUANTITY:"INC_QUANTITY",

   //Dec_Cart_Data
   DEC_QUANTITY:"DEC_QUANTITY"
}

export default actions