const Actions = {
    RESET_STATE: "RESET_STATE",

    GET_CATEGORY_DATA:"GET_CATEGORY_DATA",
    GET_CATEGORY_SUCCESS:"GET_CATEGORY_SUCCESS",
    GET_CATEGORY_FAIL:"GET_CATEGORY_FAIL",

    POST_CATEGORY_DATA:"POST_CATEGORY_DATA",
    POST_CATEGORY_SUCCESS:"POST_CATEGORY_SUCCESS",
    POST_CATEGORY_FAIL:"POST_CATEGORY_FAIL",

    UPDATE_CATEGORY_DATA:"UPDATE_CATEGORY_DATA",
    UPDATE_CATEGORY_DATA_SUCCESS:"UPDATE_CATEGORY_DATA_SUCCESS",
    UPDATE_CATEGORY_DATA_FAIL:"UPDATE_CATEGORY_DATA_FAIL",
}

export default Actions