const Actions = {
    RESET_STATE: "RESET_STATE",

    GET_TOKEN: "GET_TOKEN",
    GET_TOKEN_SUCCESS: "GET_TOKEN_SUCCESS",
    GET_TOKEN_FAIL: "GET_TOKEN_FAIL",

    //logout user
    LOGOUT_USER: "LOGOUT_USER",
    LOGOUT_USER_SUCCESS:"LOGOUT_USER_SUCCESS",
    LOGOUT_USER_FAIL:"LOGOUT_USER_FAIL"
}

export default Actions;