export const Actions = {
    POST_REGISTERED_USER_DATA:"POST_REGISTERED_USER_DATA",
    POST_REGISTERED_USER_DATA_SUCCESS:"POST_REGISTERED_USER_DATA_SUCCESS",
    POST_REGISTERED_USER_DATA_FAILURE:"POST_REGISTERED_USER_DATA_FAILURE",

     //logout functionality
     LOGOUT_USER:"LOGOUT_USER"
}